### ISSUE TITLE
Introduce a UserCollectionProvider component

### ISSUE THREAD

**Issue by Basler182** [StanfordSpezi/SpeziKt#128]
### Problem

We are constructing user collection references in multiple places across the codebase, leading to redundancy and potential inconsistency.

### Solution

Introduce a `UserCollectionProvider` class that centralizes the logic for retrieving user collections. This class would inject the necessary dependencies and streamline the process. For example:

```kotlin
class UserCollectionProvider @Inject constructor(
    private val firebaseFirestore: FirebaseFirestore,
    private val userSessionManager: UserSessionManager,
) {
    fun getUserCollection(): Result<CollectionReference> = runCatching {
        val uid = userSessionManager.getUserUid() ?: error("User not available")
        firebaseFirestore.collection("$USERS_PATH/$uid")
    }
}
```

This would eliminate the need to redeclare constants and manage multiple dependencies across different locations. Similar work has been done in `ObservationCollectionProvider`.

### Additional context

The implementation would help simplify code and reduce duplication, ensuring a single source of truth for user collection management.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by pauljohanneskraft** [comment]
Just as an FYI to not do too much work and then regret that it may be replaced anyways: On iOS, we have a snapshot listener on the user account within SpeziAccount and expose that property through that. So we may be able to just get that user information (as well as the notification settings) from the AccountDetails value...

I'm currently working on bringing SpeziAccount and SpeziFirebase to a point where we can use it on Android as well

**Comment by Basler182** [comment]
> Just as an FYI to not do too much work and then regret that it may be replaced anyways: On iOS, we have a snapshot listener on the user account within SpeziAccount and expose that property through that. So we may be able to just get the organization (as well as the notification settings) from the AccountDetails value instead of fetching them manually right before fetching the organization.
> 
> I'm currently working on bringing SpeziAccount and SpeziFirebase to a point where we can use it on Android as well

good to know, then I think I would just close the issue to avoid confusion and probably it makes sense to remove ticket #27 and #25 as well, right?

CC @eldcn
