### ISSUE TITLE
Create placeholder files for google-services.json and String Resources secrets

### ISSUE THREAD

**Issue by Basler182** [StanfordSpezi/SpeziKt#26]
### Problem

Currently, the project lacks placeholder files for google-services.json and String Resources secrets. This can cause confusion and errors during the setup process, as developers may not know where or how to include these essential configuration files.

### Solution

Create placeholder files for google-services.json and the necessary String Resources secrets. These placeholders should be clearly marked with instructions on how to replace them with actual configuration values.

### Additional context

Including placeholder files will streamline the setup process for new developers, ensuring that they know exactly where to place their configuration values and reducing the likelihood of setup errors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by eldcn** [comment]
Instead of placeholders, we can consider introducing [source sets for debug builds](https://developer.android.com/build/build-variants#sourcesets).

**Comment by PSchmiedmayer** [comment]
We have added a placeholder file for the google services json for Firebase in #30 that ensures that the builds are running locally and build successful. The file is replaced when building an app bundle for the Play Store. Does not address string resources secrets.
