### ISSUE TITLE
Crash on Pressing Sign in With Google

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziKt#40]
### Description

The application currently crashes when downloaded from the Google Play store and trying to use the Sign in With Google button.

### Reproduction

1. Open the application and navigate to the login screen.
2. Press the sign in with Google button.

### Expected behavior

Should show the credential manager sheet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Basler182** [comment]
Duplicated by #26. There currently is not O-Auth Token added during the build.
