### ISSUE TITLE
Video Description can't be null in future

### ISSUE THREAD

**Issue by Basler182** [StanfordSpezi/SpeziKt#59]
### Problem

In future, the description of the videos can no longer be null

### Solution

The mapper must be adapted so that it does not accept videos without a description and the model can then be adapted accordingly so that it no longer accepts null values and the null check can then be removed in the code

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
CC @pauljohanneskraft to notify us once this is part of the Firebase Schema. Also affects the iOS app with @nriedman.
