### ISSUE TITLE
Introduce Detekt

### ISSUE THREAD

**Issue by eldcn** [StanfordSpezi/SpeziKt#6]
### Problem

Ensuring consistency in coding style can easily become challenging. Without a standardized approach, the codebase may accumulate technical debt, leading to reduced maintainability.

### Solution

Introducing [detekt](https://detekt.dev/). Detekt is a static code analysis tool specifically designed for Kotlin, which is able to detect code smells, and enforces coding style conventions. It can be setup locally and integrated into CI/CD pipelines. We can therefore automate code quality checks and enforce best practices consistently across the codebase

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
In addition, it might make sense to add a CodeQL setup to this repo?

We have started to use it for some of our other packages and it seems to be a well maintained additional layer of detecting possible security issues and common mistakes right in PRs.
