### ISSUE TITLE
Add RouteParamProvider Component for JSON Decoding

### ISSUE THREAD

**Issue by Basler182** [StanfordSpezi/SpeziKt#60]
### Problem

The current approach using extension functions for decoding JSON from SavedStateHandle involves repetitive code and adds complexity to our tests. We need to stub the JSON data in each test case individually, which is inefficient and error-prone.

### Solution

```kotlin
@ViewModelScoped
class RouteParamProvider @Inject constructor(
   val savedStateHandle: SavedStateHandle,
) {
   inline fun <reified T> decode(key: String): T {
       val jsonString = savedStateHandle.get<String>(key) ?: throw IllegalArgumentException("Argument not found")
       return Json.decodeFromString(jsonString)
   }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by eldcn** [comment]
Closing this issue since we need the function to be inlined with a reified T parameter, however, mockk does not support stubbing of inline functions
