### ISSUE TITLE
Restrict Dokka Documentation Build to Main Branch Only

### ISSUE THREAD

**Issue by Basler182** [StanfordSpezi/SpeziKt#7]
### Problem

Currently, the Dokka Documentation Build is triggered already on pull_requests to main branch, which consumes unnecessary CI/CD resources and potentially slows down the development process by queuing up builds that aren't immediately necessary. In addition, the documentation should always contain the main branch and not the documentation of branches for which there is only one PR

### Solution

Configure the CI/CD pipeline to only trigger the Dokka Documentation Build when changes are pushed to the main branch. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by eldcn** [comment]
I already fixed this as part of #18 PR. Closing as it is already the case (see [main.yml](https://github.com/StanfordSpezi/SpeziKt/blob/main/.github/workflows/main.yml#L29))
