### ISSUE TITLE
Bottom sheets and record operations

### ISSUE THREAD

**Issue by eldcn** [StanfordSpezi/SpeziKt#74]
### Problem

Currently not all expected bottom sheets are implemented. Additionally, record descriptions are also being displayed as bottom sheets

### Solution

- Implement missing bottom sheets and their underlying functionality, e.g. add record
- Implement delete record functionality via firebase
- Consider alternative display of descriptions instead of a bottom sheet, e.g. text box under the chart

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Agree, the overall layout in the iOS app of this screen seems to be more consistent and less overloaded with buttons and different options. The floating add button already gives some weight to the screen, the info button overloads this a bit.

**Comment by PSchmiedmayer** [comment]
In addition; I would aim to find a more "native" approach to delete elements in the list. The swipe-to-delete seems a bit off on Android & it also seems to conflict with the swipe between the weight, BP, and other selections on the top of the heart health screen.

**Comment by Basler182** [comment]
As there was very little space to navigate between the tabs, we have already decided to deactivate the swipe function in one of the last merge requests. This means that there is no longer any overlap with the swipe-to-delete function. Personally, I prefer this approach as many of the apps I like to use, such as Gmail, Notes etc., offer similar functionalities. Alternatives I have seen would be either opening a dialogue with the delete option on` long press` or permanently displaying a `delete icon` on each entry. If you prefer, I can change it to the following, @PSchmiedmayer . 

I would also like to point out that the description is probably information that most users would only be interested in once or possibly not even read at all. However, if it is permanently displayed in a box below, it takes up almost a third of the screen, which is at the expense of more relevant information. In my view, the specific values and the trend would be of greater interest to the user, especially as the chart is aggregated. However, if I am alone in this opinion, I am happy to adapt it accordingly.
