### ISSUE TITLE
Symptoms in Heart Health

### ISSUE THREAD

**Issue by eldcn** [StanfordSpezi/SpeziKt#75]
### Problem

Currently, the symptoms tab is hidden because it only displays mocked data

### Solution

Implement symptoms tab to retrieve the data via firebase and display its tab in the first (0th index) position in heart health screen

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
That would be great; happy to orient yourself on the iOS design choices there with a menu to select the different sub-scores.

**Comment by Basler182** [comment]
It would be great if you could add demo data for the symptoms. 🚀 As far as I have seen, there are none yet?  @pauljohanneskraft?

**Comment by pauljohanneskraft** [comment]
> It would be great if you could add demo data for the symptoms. 🚀 As far as I have seen, there are none yet?  @pauljohanneskraft?

Symptom Scores and Medication Recommendations will now be seeded as well with this PR: https://github.com/StanfordBDHG/ENGAGE-HF-Firebase/pull/61
