### ISSUE TITLE
Add weight bottom sheet

### ISSUE THREAD

**Issue by eldcn** [StanfordSpezi/SpeziKt#80]
### Problem

Currently, the weight unit in add weight bottom sheet is hardcoded to `lbs`. Also `save` functionality is not implemented but we just log instead

### Solution

- Consider offering the unit based on the device locale either `kg` or `lbs`.
- Save the weight in firebase

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Thank you @eldcn for creating all these issues!
I would also add that it would be great if the form itself is a single page and not a step-by-step process. The date pickers and time picker could be single field that just allows you to modify it using the typical date picker overlay.

I could also see that the sheet only needs to use up the size of the fields + keyboard and not the complete screen or rather have the fields aligned at the top of a full-screen sheet as we do for iOS.

**Comment by Basler182** [comment]
@PSchmiedmayer  I have rethought adding the data see the following PR: #87  If this fits, I would adjust the weight in the same way

**Comment by PSchmiedmayer** [comment]
Thank you for working on this @Basler182; very cool!
